### ISSUE TITLE
question about missing dependency wheel files (shexjsg depends on antlr)

### ISSUE THREAD

**Issue by sideshowtom** [linkml/linkml-runtime#127]
Not a python user, but I'm just trying to do enough to use linkml-runtime in a browser with javascript.  I'm using Pyodide and micropip.install and it comes up with an error about missing wheel files in pyldmod and others:

oops: PythonError: Traceback (most recent call last):
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 494, in eval_code_async
    await CodeRunner(
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 347, in run_async
    await coroutine
  File "<exec>", line 7, in <module>
  File "/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 191, in install
    raise ValueError(
ValueError: Couldn't find a pure Python 3 wheel for: 'pyldmod', 'antlr4-python3-runtime~=4.9', 'pyldmod', 'pyyaml<6.0.0,>=5.1.0', 'wrapt<2,>=1.10'

**Comment by cmungall** [comment]
I'm afraid I don't know much about Pyodide (it would be cool to run linkml-runtime in the browser!)

I think the issue can be traced to this part of the dependency tree:

```
shexjsg 0.8.1 ShExJSG - Astract Syntax Tree for the ShEx 2.0 language
└── pyjsg >=0.11.9
    ├── antlr4-python3-runtime >=4.9,<5.0
    └── jsonasobj >=1.2.1
        └── hbreader *
```

linkml-runtime depends on shexjsg which depends on pyjsg which depends on antlr4-python3-runtime

unfortunately it seems there is no wheel for antlr4-python3-runtime

If we go to the console

https://pyodide.org/en/stable/console.html

```python
>>> f=micropip.install('antlr4-python3-runtime')
>>> f.print_stack()
Traceback for <Task finished name='Task-88' coro=<_PackageManager.install() done, defined at /lib/python3.9/site-packages/micropip/_micropip.py:178> exception=Valu
eError("Couldn't find a pure Python 3 wheel for 'antlr4-python3-runtime'. You can use `micropip.install(..., keep_going=True)` to get a list of all packages with m
issing wheels.")> (most recent call last):
  File "/lib/python3.9/asyncio/tasks.py", line 324, in __step
    self = None  # Needed to break cycles when an exception occurs.
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 185, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 175, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.9/asyncio/tasks.py", line 340, in __wakeup
    self = None  # Needed to break cycles when an exception occurs.
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 324, in __step
    self = None  # Needed to break cycles when an exception occurs.
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 290, in add_requirement
    raise ValueError(
ValueError: Couldn't find a pure Python 3 wheel for 'antlr4-python3-runtime'. You can use `micropip.install(..., keep_going=True)` to get a list of all packages wi
th missing wheels.
```

note that we are not constraining on the version here

I am not even sure where the github repo is for antlr4-python3-runtime to lodge an issue.

I am assigning this to @hsolbrig to see if there is a way to get this out of the dependency tree - as far as I know we have no need of antlr parsing and I am not sure we even use shexjsg?

**Comment by cmungall** [comment]
Would you mind sharing more details on what you are planning re running the runtime in the browser?

You may be interested in the **very early stages** ts/js runtime lib:

https://github.com/cmungall/linkml-runtime.js

**Comment by cmungall** [comment]
OK, it turns out that in metamodelcore we do make use of two functions from shexjsg:

https://github.com/linkml/linkml-runtime/blob/8cc930febb9f3eacc32bbaebfe71f7af24baa43a/linkml_runtime/utils/metamodelcore.py#L172-L175

which calls:

https://github.com/hsolbrig/ShExJSG/blob/9e9dae3d66c03c8f3a9d0dc38c0c31108e254d04/ShExJSG/ShExJ.py#L55-L56

@hsolbrig - can we remove the dependency and replace these with regex checks?

**Comment by sideshowtom** [comment]
Thank you for looking into this, and thank you for LinkML.  

I'm just a hobbyist, but I have been following the Solid project closely, and a number of developers there find RDF intimidating and I thought a utility that runs in the browser and converts resources in Solid pods between LinkML and RDF resources would be a good thing to work on.

I don't think I would be making the goto tool, probably just a small demo, so I thought using Pyodide might help.  I'll take a look at the Javascript repo.

**Comment by cmungall** [comment]
Thanks, and thanks for spurring us to look at Pyodide

Solid is a cool project, would be very happy to contribute to making it easier in any way!

I think we may be close to a PR that removes the dependency on antlr, stay tuned!

**Comment by joeflack4** [comment]
That's so cool that we are this close to running LinkML in the browser!

**Comment by cmungall** [comment]
Thinking about this dependency on shexjsg a little more - recall we only use this for checking regexes

We can get the same thing by simply including a [linkml:pattern](https://w3id.org/linkml/pattern) at in the type definitions of uri, curie, and uriorcurie.

**Comment by cmungall** [comment]
unfortunately not quite there yet:

```python
>>> import micropip
>>> f=micropip.install('linkml-runtime')
>>> f.result()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 185, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 175, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 295, in add_requirement
    await self.add_wheel(req.name, wheel, ver, req.extras, ctx, transaction)
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 305, in add_wheel
    await self.add_requirement(recurs_req, ctx, transaction)
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 290, in add_requirement
    raise ValueError(
ValueError: Couldn't find a pure Python 3 wheel for 'pyldmod'. You can use `micropip.install(..., keep_going=True)` to get a list of all packages with missing whee
ls.
>>> 
 
```

**Comment by cmungall** [comment]
getting closer:

```python
>>> import micropip
>>> f=micropip.install('linkml-runtime==1.2.0rc6')
>>> f.result()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 185, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 175, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 295, in add_requirement
    await self.add_wheel(req.name, wheel, ver, req.extras, ctx, transaction)
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 305, in add_wheel
    await self.add_requirement(recurs_req, ctx, transaction)
  File "/lib/python3.9/site-packages/micropip/_micropip.py", line 290, in add_requirement
    raise ValueError(
ValueError: Couldn't find a pure Python 3 wheel for 'pyyaml<6.0.0,>=5.1.0'. You can use `micropip.install(..., keep_going=True)` to get a list of all packages with
 missing wheels.
```

I am not sure why we force 5.x for pyyaml. Next we can try that, as there is definitely a wheel for pyyaml 6:

```
Welcome to the Pyodide terminal emulator 🐍
Python 3.9.5 (default, Feb 22 2022 14:12:02) on WebAssembly VM
Type "help", "copyright", "credits" or "license" for more information.
>>> import micropip
>>> f=micropip.install('pyyaml>=5.1.0')
>>> import yaml
>>> yaml.dump([1,2])
'- 1\n- 2\n'
>>> 
```

**Comment by cmungall** [comment]
Partial success!

```python
>>> import micropip
>>> f=micropip.install('linkml-runtime==1.2.2')
>>> f.result()
```

works!

however, unfortunately it's not possible to progress further as the runtime requires an ssl connection:

```python
>>> import linkml_runtime
Traceback (most recent call last):
  File "/lib/python3.9/site-packages/urllib3/connectionpool.py", line 692, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/lib/python3.9/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
    return conn or self._new_conn()
  File "/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1009, in _new_conn
    raise SSLError(
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /prefixcommons/biocontext/master/
registry/monarch_context.jsonld (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.9/site-packages/linkml_runtime/__init__.py", line 2, in <module>
    from linkml_runtime.utils.schemaview import SchemaView
  File "/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 8, in <module>
    from linkml_runtime.utils.namespaces import Namespaces
  File "/lib/python3.9/site-packages/linkml_runtime/utils/namespaces.py", line 4, in <module>
    from prefixcommons import curie_util
  File "/lib/python3.9/site-packages/prefixcommons/__init__.py", line 4, in <module>
    from .curie_util import expand_uri, contract_uri, NoPrefix
  File "/lib/python3.9/site-packages/prefixcommons/curie_util.py", line 79, in <module>
    default_curie_maps = [read_biocontext('monarch_context'),read_biocontext('obo_context')]
  File "/lib/python3.9/site-packages/prefixcommons/curie_util.py", line 75, in read_biocontext
    return read_remote_jsonld_context("https://raw.githubusercontent.com/prefixcommons/biocontext/master/registry/"+name+".jsonld")
  File "/lib/python3.9/site-packages/prefixcommons/curie_util.py", line 56, in read_remote_jsonld_context
    with closing(requests.get(url, stream=False)) as resp:
  File "/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /prefixcommons/biocontext/master/regi
stry/monarch_context.jsonld (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
```

We have a separate issue about reducing network dependencies

 * https://github.com/linkml/linkml/issues/502

however I don't think there is a way to get rid of this altogether - schemas have imports and imports are typically to https URLs

This may be relevant:
https://github.com/pyodide/pyodide/issues/529

**Comment by sideshowtom** [comment]
Since https://github.com/pyodide/pyodide/issues/529 has been fixed but is awaiting release, maybe this can be revisited after that release ("some time in April")?
https://github.com/pyodide/pyodide/issues/529#issuecomment-1068563138
