### ISSUE TITLE
Unit tests with Python 3.10 fail

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml-runtime#76]
When Python 3.10 is included in the github actions with `python-version: [ 3.7.1, 3.8, 3.9, "3.10" ]`, the following message is generated:

```Resolving dependencies...

FAIL

[ResolutionFailure]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line 743, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
[ResolutionFailure]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line 704, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line 685, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 1370, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 1099, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 877, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml
```

Since this error ONLY occurs with Python 3.10, the issue has to lie in:
a) Maybe the quotes around the 3.10 are causing grief (not likely)?
b) Maybe pipenv version isn't compatible?
c) ???

Looking up the PEP 517 discussions haven't been fruitful. FWIW, the pipenv folks don't seem particularly friendly on this front...

**Comment by sujaypatil96** [comment]
@hsolbrig: I used `pyenv` to switch to Python version 3.10 and run the current test suits. See the following log:

```
➜  linkml-runtime git:(main) ✗ poetry run python -m unittest discover
EEEEEE.EEEEEEsEE...xE.....EEE.../Users/sujaypatil/Desktop/linkml-runtime/tests/test_utils/test_metamodelcore.py:153: UserWarning: Code: datetime is not defined in namespace XSD
  self.assertEqual('2019-07-06T17:22:39.007300', XSDDateTime(Literal(v, datatype=XSD.datetime)))
..s....EE.
======================================================================
ERROR: linkml_runtime.dumpers (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: linkml_runtime.dumpers
Traceback (most recent call last):
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/sujaypatil/Desktop/linkml-runtime/linkml_runtime/dumpers/__init__.py", line 3, in <module>
    from linkml_runtime.dumpers.rdflib_dumper import RDFLibDumper
  File "/Users/sujaypatil/Desktop/linkml-runtime/linkml_runtime/dumpers/rdflib_dumper.py", line 11, in <module>
    from linkml_runtime.utils.schemaview import SchemaView, ElementName, PermissibleValue, PermissibleValueText
  File "/Users/sujaypatil/Desktop/linkml-runtime/linkml_runtime/utils/schemaview.py", line 10, in <module>
    from linkml_runtime.linkml_model.meta import *
  File "/Users/sujaypatil/Desktop/linkml-runtime/linkml_runtime/linkml_model/__init__.py", line 3, in <module>
    from .extensions import Extension, Extensible
  File "/Users/sujaypatil/Desktop/linkml-runtime/linkml_runtime/linkml_model/extensions.py", line 44, in <module>
    class Extension(YAMLRoot):
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/dataclasses.py", line 1178, in dataclass
    return wrap(cls)
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/dataclasses.py", line 1169, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/dataclasses.py", line 1019, in _process_class
    _init_fn(all_init_fields,
TypeError: dataclasses_init_fn_with_kwargs() missing 1 required positional argument: 'slots'
```

I ran the suite using `poetry` and it looks like there's a syntactical error we need to correct first? I can look into it.

**Comment by dalito** [comment]
On windows all tests pass on Python 3.10 after applying #145
